const drawMenuConstants = {
  DRAW_MENU_PENCIL_TOOL: 'DRAW_MENU_PENCIL_TOOL',
  DRAW_MENU_SELECT_TOOL: 'DRAW_MENU_SELECT_TOOL',
  DRAW_MENU_MOVE_TOOL: 'DRAW_MENU_MOVE_TOOL'
};

export default drawMenuConstants;
