const configObj = {
  ON_MAIL_CHANGE_TYPE: 'ON_MAIL_CHANGE_TYPE',
  ON_PASS_CHANGE_TYPE: 'ON_PASS_CHANGE_TYPE',
  ON_NAME_CHANGE_TYPE: 'ON_NAME_CHANGE_TYPE',
  ON_USER_REGISTER_TYPE: 'ON_USER_REGISTER_TYPE',
  ON_USER_LOGIN_TYPE: 'ON_USER_LOGIN_TYPE',
  ON_USER_LOGIN_PENDING : 'ON_USER_LOGIN_PENDING',
  ON_USER_LOGIN_SUCCESS: 'ON_USER_LOGIN_SUCCESS',
  ON_USER_LOGIN_FAIL: 'ON_USER_LOGIN_FAIL',
  ON_USER_REGISTER_PENDING : 'ON_USER_REGISTER_PENDING',
  ON_USER_REGISTER_SUCCESS: 'ON_USER_REGISTER_SUCCESS',
  ON_USER_REGISTER_FAIL: 'ON_USER_REGISTER_FAIL',
  LOGIN_RESPONSE_OK: 1,
  LOGIN_RESPONSE_FAIL: 0,
  REGISTER_RESPONSE_OK: 1,
  REGISTER_RESPONSE_FAIL: 0
}

export default configObj;
