const configObj = {
  ON_MAIL_CHANGE_TYPE: 'ON_MAIL_CHANGE_TYPE',
  ON_PASS_CHANGE_TYPE: 'ON_PASS_CHANGE_TYPE',
  ON_NAME_CHANGE_TYPE: 'ON_NAME_CHANGE_TYPE',
  ON_USER_REGISTER_TYPE: 'ON_USER_REGISTER_TYPE',
  ON_USER_LOGIN_TYPE: 'ON_USER_LOGIN_TYPE',
  ON_USER_LOGIN_PENDING : 'ON_USER_LOGIN_PENDING',
  ON_USER_LOGIN_SUCCESS: 'ON_USER_LOGIN_SUCCESS',
  ON_USER_LOGIN_FAIL: 'ON_USER_LOGIN_FAIL',
  ON_USER_REGISTER_PENDING : 'ON_USER_REGISTER_PENDING',
  ON_USER_REGISTER_SUCCESS: 'ON_USER_REGISTER_SUCCESS',
  ON_USER_REGISTER_FAIL: 'ON_USER_REGISTER_FAIL',
  LOGIN_RESPONSE_OK: 1,
  LOGIN_RESPONSE_FAIL: 0,
  REGISTER_RESPONSE_OK: 1,
  REGISTER_RESPONSE_FAIL: 0,
  ON_COLOR_CHANGE: 'ON_COLOR_CHANGE',
  ON_DRAW_AREA_MOUSE_DOWN: 'ON_DRAW_AREA_MOUSE_DOWN',
  ON_DRAW_AREA_MOUSE_UP: 'ON_DRAW_AREA_MOUSE_UP',
  ON_DRAW_AREA_MOUSE_MOVE: 'ON_DRAW_AREA_MOUSE_MOVE',
  ON_DRAW_AREA_INIT: 'ON_DRAW_AREA_INIT',
  ON_CANVAS_RESIZE: 'ON_CANVAS_RESIZE',
  ON_MENU_LOCK: 'ON_MENU_LOCK',
  ON_MENU_UNLOCK: 'ON_MENU_UNLOCK',
  ON_MOUSE_DRAW_MENU_ENTER: 'ON_MOUSE_DRAW_MENU_ENTER',
  ON_MOUSE_DRAW_MENU_LEAVE: 'ON_MOUSE_DRAW_MENU_LEAVE'
}

export default configObj;
